### ISSUE TITLE
Cannot join MultiProgress with hidden ProgressBars

### ISSUE THREAD

**Issue by bbannier** [mitsuhiko/indicatif#39] opened 2018-03-01 09:05 UTC
I seem to be unable to join a `MultiProgress` containing hidden `ProgressBar`s. I would have expected this to work, or alternatively to be able to figure out a workaround from the documentation.

    #[test]
    fn hangs() {
        let m = MultiProgress::new();
    
        let p = m.add(ProgressBar::new(1));
        p.set_draw_target(ProgressDrawTarget::hidden());
        p.finish_and_clear();
     
        m.join_and_clear();
    }

**Comment by andreivasiliu** [comment] 2018-12-06 22:00
The confusion here comes from the fact that `Hidden` is a draw target, but so is `Remote` (which is applied by `m.add(...)`, so setting it to hidden makes it override the remote, thus the multiprogress no longer ever receives anything.

The workaround is to never call any draw methods, which will keep a progress bar hidden, even inside a multi-line.

Those two bits of information should be added to the documentation of `ProgressDrawTarget::hidden()`. I can do that next weekend.

**Comment by bbannier** [comment] 2018-12-15 12:31
Thanks for the clarification and usage guidelines @andreivasiliu.

The way I was using progress bars was to set up their "visibility" on a higher scope by setting their draw target, and then in low-level functions just updating them -- there is currently no concept of visibility in these places. From what you write this is neither intended nor possible currently, so I might need to add some indirections to adapt the bars for the actual model. It would have been great if indicatif supported some way to avoid that.

**Comment by mitsuhiko** [comment] 2018-12-26 11:01
Closing this as works as intended for now. I'm not super happy how the draw targets work. Ideally one can hide the progress bar differently anyways than setting a draw target.

**Closed by mitsuhiko** 2018-12-26 11:01 UTC
