### ISSUE TITLE
Spinners in a multibar don't spin while a child process runs

### ISSUE THREAD

**Issue by migerh** [mitsuhiko/indicatif#52] opened 2018-06-10 08:48 UTC
I observed that spinners do not spin while a child process runs that was spawned with `std::process::Command`. Especially when they are in a multibar. I created a small example that shows the issue: https://github.com/migerh/indicatif-multibar

The [use_multibar_with_timeout_for_finish() example](https://github.com/migerh/indicatif-multibar/blob/master/src/main.rs#L49-L63) shows that while the child process is running, the spinners in the multibar do not update. They start spinning as soon as the child process finishes, though.

**Comment by andreivasiliu** [comment] 2018-12-06 22:02
The confusion here comes from the fact that calling `.join()` must be done in a separate thread, as that is what is doing the rendering. Same as #77.

#33 would have prevented this.

**Comment by mitsuhiko** [comment] 2018-12-26 10:59
Going to close this as duplicate of #33.

**Closed by mitsuhiko** 2018-12-26 10:59 UTC
